import Head from "next/head"
import Image from "next/image"
import styles from "../styles/images.module.scss"

function MyImage({ src }) {
  return (
    <Image
      src={src}
      alt="aids cubid arrow"
      layout="responsive"
      width={200}
      height={100}
      objectFit="contain"
    />
  )
}

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <div className={styles.imagesFlex}>
          <div className={styles.imageWrapper}>
            <MyImage src="/images/section-img-1.jpg" />
          </div>
          <div className={styles.imageWrapper}>
            <MyImage src="/images/section-img-2.jpg" />
          </div>
          <div className={styles.imageWrapper}>
            <MyImage src="/images/section-img-3.jpg" />
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
