import Head from "next/head"
import Image from "next/image"
import styles from "../styles/home.module.scss"
import HomeNews from "../components/homeNews"
import Nav from "../components/nav"
import RandomNews from "../components/randomNews"
import YourLuckToday from "../components/yourLuckToday"
import Quotes from "../components/quotes"
import Footer from "../components/footer"
import UnnamedSectionLol from "../components/unnamedSectionLol"

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav />
        <RandomNews />
        <HomeNews />
        <YourLuckToday />
        <UnnamedSectionLol />
        <Quotes />
      </main>

      <Footer />
    </div>
  )
}

export default Home
